generate:
  - types
  - client
accessModifier: internal
filter:
  paths:
    - v1/apps
    - v1/apps/{id}/appStoreVersions
    - v1/builds
#    - v1/builds/{id}/preReleaseVersion
#    - v1/apps/{id}/builds -
#    - v1/apps/{id}/preReleaseVersions
