name: Lint code

on: push

# Allow one concurrent deployment
concurrency:
  group: "linting"
  cancel-in-progress: true

jobs:
  SwiftLint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Lint code using SwiftLint
        run: swiftlint lint --reporter github-actions-logging
